"""empty message

Revision ID: 01628e1f88ea
Revises: 
Create Date: 2023-02-28 23:10:08.672260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01628e1f88ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('raffle_id', sa.Integer(), nullable=True))
        batch_op.alter_column('account',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('buyer_wallet',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.drop_index('idx_buys_accounts')

    with op.batch_alter_table('cancels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('dt_cancel',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('account',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'raffles', ['account'], ['account'])

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('collection_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.alter_column('collection_alias',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('collection_proper_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)

    with op.batch_alter_table('endings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('dt_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('account',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'raffles', ['account'], ['account'])

    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.alter_column('nft_mint',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('collection',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)

    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.alter_column('collection',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)

    with op.batch_alter_table('rafflers', schema=None) as batch_op:
        batch_op.alter_column('wallet',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.alter_column('twitter',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('dao_status',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)

    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('account',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.alter_column('host_wallet',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('nft_mint',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.drop_index('idx_raffles_acct')
        batch_op.create_index(batch_op.f('ix_raffles_account'), ['account'], unique=True)
        batch_op.create_index(batch_op.f('ix_raffles_id'), ['id'], unique=False)

    with op.batch_alter_table('raffles_scraped', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sales', sa.DOUBLE_PRECISION(), sa.Computed('tkt_sold * tkt_price', ), nullable=True))
        batch_op.alter_column('account',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('floor',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('tkt_cost',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('tkt_token',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('status_text',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)

    with op.batch_alter_table('winners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('dt_win',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('account',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('winner_wallet',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'rafflers', ['winner_wallet'], ['wallet'])
        batch_op.create_foreign_key(None, 'raffles', ['account'], ['account'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winners', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('winner_wallet',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('account',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dt_win',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('raffles_scraped', schema=None) as batch_op:
        batch_op.alter_column('status_text',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tkt_token',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tkt_cost',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('floor',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('account',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('total_sales')

    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raffles_id'))
        batch_op.drop_index(batch_op.f('ix_raffles_account'))
        batch_op.create_index('idx_raffles_acct', ['account'], unique=False)
        batch_op.alter_column('nft_mint',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('host_wallet',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('account',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('rafflers', schema=None) as batch_op:
        batch_op.alter_column('dao_status',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('twitter',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('wallet',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.alter_column('collection',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.alter_column('collection',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('nft_mint',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('endings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('account',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dt_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('collection_proper_name',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('collection_alias',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('collection_name',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('cancels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('account',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dt_cancel',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.create_index('idx_buys_accounts', ['account'], unique=False)
        batch_op.alter_column('buyer_wallet',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('account',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('raffle_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
