"""testing FactRaffles MV

Revision ID: 265afdff3e76
Revises: 7123f5b7a41b
Create Date: 2023-03-07 13:10:35.075612

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '265afdff3e76'
down_revision = '7123f5b7a41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_raffles = PGMaterializedView(
                schema="public",
                signature="fact_raffles",
                definition='SELECT raffles.dt_start AS "Start Date", raffles.account AS "Account", rafflers.twitter AS "Host Name", sum(buys.amt_buy) AS total_sales \nFROM raffles LEFT OUTER JOIN cancels ON raffles.id = cancels.raffle_id LEFT OUTER JOIN endings ON raffles.id = endings.raffle_id LEFT OUTER JOIN buys ON raffles.id = buys.raffle_id LEFT OUTER JOIN winners ON raffles.id = winners.raffle_id, rafflers \nWHERE raffles.id != cancels.raffle_id GROUP BY raffles.dt_start, raffles.account, rafflers.twitter',
                with_data=True
            )

    op.replace_entity(public_fact_raffles)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_raffles = PGMaterializedView(
                schema="public",
                signature="fact_raffles",
                definition='SELECT raffles.dt_start AS "Start Date",\n    raffles.account AS "Account",\n    rafflers.twitter AS "Host Name"\n   FROM (((raffles\n     LEFT JOIN cancels ON ((raffles.id = cancels.raffle_id)))\n     LEFT JOIN endings ON ((raffles.id = endings.raffle_id)))\n     LEFT JOIN winners ON ((raffles.id = winners.raffle_id))),\n    rafflers\n  WHERE (raffles.id <> cancels.raffle_id)',
                with_data=True
            )

    op.replace_entity(public_fact_raffles)
    # ### end Alembic commands ###
