"""adding winner name to FactRaffles mv

Revision ID: 3742d96a0437
Revises: f118ddad3d89
Create Date: 2023-03-12 19:48:16.588693

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '3742d96a0437'
down_revision = 'f118ddad3d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_raffles = PGMaterializedView(
                schema="public",
                signature="fact_raffles",
                definition='SELECT raffles.id AS raffle_id, raffles.dt_start AS start_date, endings.dt_end AS end_date, raffles.account AS account, rafflers.twitter AS host_name, rafflers.dao_status AS host_dao_status, winners.winner_wallet AS winner_wallet, rafflers_1.twitter AS winner_name \nFROM raffles LEFT OUTER JOIN cancels ON raffles.id = cancels.raffle_id LEFT OUTER JOIN endings ON raffles.id = endings.raffle_id LEFT OUTER JOIN winners ON raffles.id = winners.raffle_id LEFT OUTER JOIN rafflers ON raffles.host_id = rafflers.id LEFT OUTER JOIN rafflers AS rafflers_1 ON winners.winner_id = rafflers_1.id \nWHERE cancels.account IS NULL',
                with_data=True
            )

    op.replace_entity(public_fact_raffles)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_raffles = PGMaterializedView(
                schema="public",
                signature="fact_raffles",
                definition='SELECT raffles.id AS raffle_id,\n    raffles.dt_start AS start_date,\n    endings.dt_end AS end_date,\n    raffles.account,\n    rafflers.twitter AS host_name,\n    rafflers.dao_status AS host_dao_status,\n    winners.winner_wallet\n   FROM ((((raffles\n     LEFT JOIN cancels ON ((raffles.id = cancels.raffle_id)))\n     LEFT JOIN endings ON ((raffles.id = endings.raffle_id)))\n     LEFT JOIN winners ON ((raffles.id = winners.raffle_id)))\n     LEFT JOIN rafflers ON ((raffles.host_id = rafflers.id)))\n  WHERE (cancels.account IS NULL)',
                with_data=True
            )

    op.replace_entity(public_fact_raffles)
    # ### end Alembic commands ###
