"""empty message

Revision ID: 3db524e9937d
Revises: 3bace6c99431
Create Date: 2023-03-03 08:51:37.223075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db524e9937d'
down_revision = '3bace6c99431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_cancel', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account', sa.String(length=45), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cancels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cancels_account'), ['account'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cancels_account'))

    op.drop_table('cancels')
    # ### end Alembic commands ###
