"""adding DataOverview materialized view to models

Revision ID: 4333fecef202
Revises: a5e4ead7c99a
Create Date: 2023-03-06 13:54:00.298295

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '4333fecef202'
down_revision = 'a5e4ead7c99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_data_overview = PGMaterializedView(
                schema="public",
                signature="data_overview",
                definition="SELECT date_trunc('day', raffles.dt_start) AS dt_start, count(distinct(raffles.account)) AS raffle_count, count(distinct(buys.account)) AS buy_count \nFROM raffles LEFT OUTER JOIN buys ON raffles.id = buys.raffle_id GROUP BY date_trunc('day', raffles.dt_start)",
                with_data=True
            )

    op.replace_entity(public_data_overview)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_data_overview = PGMaterializedView(
                schema="public",
                signature="data_overview",
                definition="SELECT date_trunc('day'::text, raffles.dt_start) AS dt_start,\n    count(DISTINCT raffles.account) AS raffle_count\n   FROM raffles\n  GROUP BY (date_trunc('day'::text, raffles.dt_start))",
                with_data=True
            )

    op.replace_entity(public_data_overview)
    # ### end Alembic commands ###
