"""adding DataOverview materialized view to models

Revision ID: 4a1648c37bf8
Revises: b4f0865870eb
Create Date: 2023-03-06 13:08:55.359598

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '4a1648c37bf8'
down_revision = 'b4f0865870eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_first_view = PGMaterializedView(
                schema="public",
                signature="first_view",
                definition="SELECT date_trunc('day', raffles.dt_start) AS date_trunc_1, count(distinct(raffles.account)) AS raffle_count \nFROM raffles GROUP BY date_trunc('day', raffles.dt_start)",
                with_data=True
            )

    op.replace_entity(public_first_view)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_first_view = PGMaterializedView(
                schema="public",
                signature="first_view",
                definition="SELECT date_trunc('day'::text, raffles.dt_start) AS date_trunc_1,\n    count(DISTINCT raffles.account) AS count_1\n   FROM raffles\n  GROUP BY (date_trunc('day'::text, raffles.dt_start))",
                with_data=True
            )

    op.replace_entity(public_first_view)
    # ### end Alembic commands ###
