"""testing FactRaffles MV

Revision ID: 7123f5b7a41b
Revises: d41e389ccad8
Create Date: 2023-03-07 12:50:23.127250

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '7123f5b7a41b'
down_revision = 'd41e389ccad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.drop_index('idx_fact_raffles_acct')

    public_fact_raffles = PGMaterializedView(
                schema="public",
                signature="fact_raffles",
                definition='SELECT raffles.dt_start AS "Start Date", raffles.account AS "Account", rafflers.twitter AS "Host Name" \nFROM raffles LEFT OUTER JOIN cancels ON raffles.id = cancels.raffle_id LEFT OUTER JOIN endings ON raffles.id = endings.raffle_id LEFT OUTER JOIN winners ON raffles.id = winners.raffle_id, rafflers \nWHERE raffles.id != cancels.raffle_id',
                with_data=True
            )

    op.create_entity(public_fact_raffles)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_raffles = PGMaterializedView(
                schema="public",
                signature="fact_raffles",
                definition='SELECT raffles.dt_start AS "Start Date", raffles.account AS "Account", rafflers.twitter AS "Host Name" \nFROM raffles LEFT OUTER JOIN cancels ON raffles.id = cancels.raffle_id LEFT OUTER JOIN endings ON raffles.id = endings.raffle_id LEFT OUTER JOIN winners ON raffles.id = winners.raffle_id, rafflers \nWHERE raffles.id != cancels.raffle_id',
                with_data=True
            )

    op.drop_entity(public_fact_raffles)

    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.create_index('idx_fact_raffles_acct', ['account'], unique=False)

    # ### end Alembic commands ###
