"""adding FactBuys mv

Revision ID: 7c1ecf9f1d0e
Revises: 4df93032c1ac
Create Date: 2023-03-09 07:45:45.983406

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '7c1ecf9f1d0e'
down_revision = '4df93032c1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_buys = PGMaterializedView(
                schema="public",
                signature="fact_buys",
                definition='SELECT buys.dt_buy AS date_buy, buys.amt_buy AS amount_buy, buys.buyer_wallet AS buyer_wallet, rafflers.twitter AS buyer_name, rafflers.dao_status AS buyer_dao_status, buys.raffle_id AS raffle_id, buys.id AS buy_id \nFROM buys LEFT OUTER JOIN rafflers ON buys.buyer_id = rafflers.id',
                with_data=True
            )

    op.create_entity(public_fact_buys)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_buys = PGMaterializedView(
                schema="public",
                signature="fact_buys",
                definition='SELECT buys.dt_buy AS date_buy, buys.amt_buy AS amount_buy, buys.buyer_wallet AS buyer_wallet, rafflers.twitter AS buyer_name, rafflers.dao_status AS buyer_dao_status, buys.raffle_id AS raffle_id, buys.id AS buy_id \nFROM buys LEFT OUTER JOIN rafflers ON buys.buyer_id = rafflers.id',
                with_data=True
            )

    op.drop_entity(public_fact_buys)

    # ### end Alembic commands ###
