"""adding DataOverview materialized view to models

Revision ID: a5e4ead7c99a
Revises: 3db012ddc9c2
Create Date: 2023-03-06 13:30:58.346515

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = 'a5e4ead7c99a'
down_revision = '3db012ddc9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_data_overview = PGMaterializedView(
                schema="public",
                signature="data_overview",
                definition="SELECT date_trunc('day', raffles.dt_start) AS dt_start, count(distinct(raffles.account)) AS raffle_count \nFROM raffles GROUP BY date_trunc('day', raffles.dt_start)",
                with_data=True
            )

    op.replace_entity(public_data_overview)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_data_overview = PGMaterializedView(
                schema="public",
                signature="data_overview",
                definition="SELECT date_trunc('day'::text, raffles.dt_start) AS date_trunc_1,\n    count(DISTINCT raffles.account) AS raffle_count\n   FROM raffles\n  GROUP BY (date_trunc('day'::text, raffles.dt_start))",
                with_data=True
            )

    op.replace_entity(public_data_overview)
    # ### end Alembic commands ###
