"""adding DataOverview materialized view to models

Revision ID: b4f0865870eb
Revises: c3d724bde27c
Create Date: 2023-03-06 13:05:40.471884

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = 'b4f0865870eb'
down_revision = 'c3d724bde27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))

    public_first_view = PGMaterializedView(
                schema="public",
                signature="first_view",
                definition="SELECT date_trunc('day', raffles.dt_start) AS date_trunc_1, count(distinct(raffles.account)) AS count_1 \nFROM raffles GROUP BY date_trunc('day', raffles.dt_start)",
                with_data=True
            )

    op.create_entity(public_first_view)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_first_view = PGMaterializedView(
                schema="public",
                signature="first_view",
                definition="SELECT date_trunc('day', raffles.dt_start) AS date_trunc_1, count(distinct(raffles.account)) AS count_1 \nFROM raffles GROUP BY date_trunc('day', raffles.dt_start)",
                with_data=True
            )

    op.drop_entity(public_first_view)

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
