"""fixing wins, buyers to be nullable for raffles table

Revision ID: c3d724bde27c
Revises: 66b82be03423
Create Date: 2023-03-03 19:54:16.880783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d724bde27c'
down_revision = '66b82be03423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.alter_column('buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('winners', schema=None) as batch_op:
        batch_op.alter_column('winner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winners', schema=None) as batch_op:
        batch_op.alter_column('winner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.alter_column('buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
