"""fixing reprs for new classes

Revision ID: c7384294fe70
Revises: b5a33f204e44
Create Date: 2023-03-03 19:13:21.081745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7384294fe70'
down_revision = 'b5a33f204e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rafflers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet', sa.String(length=45), nullable=True),
    sa.Column('twitter', sa.String(length=125), nullable=True),
    sa.Column('dao_status', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rafflers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rafflers_id'), ['id'], unique=True)

    op.create_table('raffles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=45), nullable=False),
    sa.Column('dt_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('host_wallet', sa.String(length=45), nullable=True),
    sa.Column('nft_mint', sa.String(length=45), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['rafflers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raffles_account'), ['account'], unique=True)
        batch_op.create_index(batch_op.f('ix_raffles_dt_start'), ['dt_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_raffles_id'), ['id'], unique=True)

    op.create_table('buys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_buy', sa.DateTime(timezone=True), nullable=False),
    sa.Column('buyer_wallet', sa.String(length=45), nullable=False),
    sa.Column('account', sa.String(length=45), nullable=False),
    sa.Column('amt_buy', sa.Float(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['rafflers.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dt_buy', 'amt_buy', 'account', 'buyer_wallet', 'raffle_id', name='_buy_row_uc')
    )
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buys_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_buys_buyer_wallet'), ['buyer_wallet'], unique=False)
        batch_op.create_index(batch_op.f('ix_buys_dt_buy'), ['dt_buy'], unique=False)

    op.create_table('cancels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_cancel', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account', sa.String(length=45), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cancels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cancels_account'), ['account'], unique=False)

    op.create_table('endings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account', sa.String(length=45), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endings_account'), ['account'], unique=False)

    op.create_table('winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_win', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account', sa.String(length=45), nullable=False),
    sa.Column('winner_wallet', sa.String(length=45), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['rafflers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('winners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_winners_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_winners_winner_wallet'), ['winner_wallet'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_winners_winner_wallet'))
        batch_op.drop_index(batch_op.f('ix_winners_account'))

    op.drop_table('winners')
    with op.batch_alter_table('endings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endings_account'))

    op.drop_table('endings')
    with op.batch_alter_table('cancels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cancels_account'))

    op.drop_table('cancels')
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buys_dt_buy'))
        batch_op.drop_index(batch_op.f('ix_buys_buyer_wallet'))
        batch_op.drop_index(batch_op.f('ix_buys_account'))

    op.drop_table('buys')
    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raffles_id'))
        batch_op.drop_index(batch_op.f('ix_raffles_dt_start'))
        batch_op.drop_index(batch_op.f('ix_raffles_account'))

    op.drop_table('raffles')
    with op.batch_alter_table('rafflers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rafflers_id'))

    op.drop_table('rafflers')
    # ### end Alembic commands ###
