"""adding host name and dao status to fact buys mv

Revision ID: cb0d39b38df7
Revises: 64b94e56c5bd
Create Date: 2023-03-12 21:01:04.034641

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = 'cb0d39b38df7'
down_revision = '64b94e56c5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_buys = PGMaterializedView(
                schema="public",
                signature="fact_buys",
                definition='SELECT buys.dt_buy AS date_buy, buys.amt_buy AS amount_buy, buys.buyer_wallet AS buyer_wallet, rafflers.twitter AS buyer_name, rafflers.dao_status AS buyer_dao_status, buys.raffle_id AS raffle_id, buys.id AS buy_id, rafflers_1.twitter AS host_name, rafflers_1.dao_status AS host_dao_status \nFROM buys LEFT OUTER JOIN rafflers ON buys.buyer_id = rafflers.id LEFT OUTER JOIN raffles ON buys.raffle_id = raffles.id LEFT OUTER JOIN rafflers AS rafflers_1 ON raffles.host_id = rafflers_1.id',
                with_data=True
            )

    op.replace_entity(public_fact_buys)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_buys = PGMaterializedView(
                schema="public",
                signature="fact_buys",
                definition='SELECT buys.dt_buy AS date_buy,\n    buys.amt_buy AS amount_buy,\n    buys.buyer_wallet,\n    rafflers.twitter AS buyer_name,\n    rafflers.dao_status AS buyer_dao_status\n   FROM ((buys\n     LEFT JOIN raffles ON ((raffles.id = buys.raffle_id)))\n     LEFT JOIN rafflers ON ((buys.buyer_id = rafflers.id)))',
                with_data=True
            )

    op.replace_entity(public_fact_buys)
    # ### end Alembic commands ###
