"""testing FactRaffles MV

Revision ID: d41e389ccad8
Revises: 1650ae512449
Create Date: 2023-03-07 12:44:23.479310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41e389ccad8'
down_revision = '1650ae512449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.create_index('idx_fact_raffles_acct', ['account'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.drop_index('idx_fact_raffles_acct')

    # ### end Alembic commands ###
