"""working through basic draft of factraffles mv

Revision ID: f11f79eb9783
Revises: bdf3a0e58992
Create Date: 2023-03-07 20:56:28.886333

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = 'f11f79eb9783'
down_revision = 'bdf3a0e58992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_raffles = PGMaterializedView(
                schema="public",
                signature="fact_raffles",
                definition='SELECT raffles.dt_start AS start_date, endings.dt_end AS end_date, raffles.account AS account, rafflers.twitter AS host_name, rafflers.dao_status AS host_dao_status, winners.winner_wallet AS winner_wallet \nFROM raffles LEFT OUTER JOIN cancels ON raffles.id = cancels.raffle_id LEFT OUTER JOIN endings ON raffles.id = endings.raffle_id LEFT OUTER JOIN winners ON raffles.id = winners.raffle_id LEFT OUTER JOIN rafflers ON raffles.host_id = rafflers.id \nWHERE cancels.account IS NULL GROUP BY raffles.dt_start, endings.dt_end, raffles.account, rafflers.twitter, rafflers.dao_status, winners.winner_wallet',
                with_data=True
            )

    op.replace_entity(public_fact_raffles)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fact_raffles = PGMaterializedView(
                schema="public",
                signature="fact_raffles",
                definition='SELECT raffles.dt_start AS "Start Date",\n    raffles.account AS "Account",\n    rafflers.twitter AS "Host Name"\n   FROM ((((raffles\n     LEFT JOIN cancels ON ((raffles.id = cancels.raffle_id)))\n     LEFT JOIN endings ON ((raffles.id = endings.raffle_id)))\n     LEFT JOIN winners ON ((raffles.id = winners.raffle_id)))\n     LEFT JOIN rafflers ON ((raffles.host_id = rafflers.id)))\n  WHERE (cancels.account IS NULL)\n  GROUP BY raffles.dt_start, raffles.account, rafflers.twitter',
                with_data=True
            )

    op.replace_entity(public_fact_raffles)
    # ### end Alembic commands ###
