"""empty message

Revision ID: f40de538cd06
Revises: 0a7fe7505488
Create Date: 2023-03-02 09:21:21.589440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40de538cd06'
down_revision = '0a7fe7505488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rafflers',
    sa.Column('wallet', sa.String(length=45), nullable=False),
    sa.Column('twitter', sa.String(length=45), nullable=True),
    sa.Column('dao_status', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('wallet')
    )
    op.create_table('raffles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=45), nullable=False),
    sa.Column('dt_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('host_wallet', sa.String(length=45), nullable=True),
    sa.Column('nft_mint', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raffles_account'), ['account'], unique=True)
        batch_op.create_index(batch_op.f('ix_raffles_dt_start'), ['dt_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_raffles_id'), ['id'], unique=True)

    op.create_table('buys',
    sa.Column('dt_buy', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amt_buy', sa.Float(), nullable=False),
    sa.Column('account', sa.String(length=45), nullable=False),
    sa.Column('buyer_wallet', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dt_buy', 'amt_buy', 'account', 'buyer_wallet', 'raffle_id', name='_buy_row_uc')
    )
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buys_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_buys_dt_buy'), ['dt_buy'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buys_dt_buy'))
        batch_op.drop_index(batch_op.f('ix_buys_account'))

    op.drop_table('buys')
    with op.batch_alter_table('raffles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raffles_id'))
        batch_op.drop_index(batch_op.f('ix_raffles_dt_start'))
        batch_op.drop_index(batch_op.f('ix_raffles_account'))

    op.drop_table('raffles')
    op.drop_table('rafflers')
    # ### end Alembic commands ###
